// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Users.API.Helpers;

namespace Users.API.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20190820053452_UsersV1")]
    partial class UsersV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Users.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<Guid>("WatchLaterId");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36de8e2f-e3ff-4718-a2e8-c9fc08610728"),
                            Email = "omar.aceves@mymail.com",
                            Password = "password",
                            UserName = "omaraceves",
                            WatchLaterId = new Guid("34487500-ba60-4962-9342-907c4665681f")
                        },
                        new
                        {
                            Id = new Guid("443ed08c-e98a-4ac1-84ed-fee7b27513f9"),
                            Email = "karen.aceves@mymail.com",
                            Password = "password",
                            UserName = "karenaceves",
                            WatchLaterId = new Guid("1c389e4c-0272-48ea-b260-6b29c0c51ad7")
                        },
                        new
                        {
                            Id = new Guid("434c538e-7aed-42d7-a667-92b0760ef88c"),
                            Email = "milo.woof@mymail.com",
                            Password = "password",
                            UserName = "milowoof",
                            WatchLaterId = new Guid("c3e95c44-1e39-4328-9d52-e0291ddf2da7")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
